### ISSUE TITLE
    Fatal error

### ISSUE THREAD

**Issue by monir112761** [VivekProHacker/College-Management-System#1]
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\xampp\htdocs\CMS\php_includes\common_frame_a.php:115 Stack trace: #0 C:\xampp\htdocs\CMS\admin.php(3): include_once() #1 {main} thrown in C:\xampp\htdocs\CMS\php_includes\common_frame_a.php on line 115

**Comment by VivekSingh777** [comment]
You have to give your database username and password here
at line 115 $conn=mysql_connect("localhost","root","");
here root is my db username and password is empty
